name: "calling_workflow"
on:
  workflow_call:
  workflow_dispatch:

jobs:
  call-workflow-1-in-local-repo:
    uses: ./.github/workflows/centralTEST.yml@main
    with:
      token: ${{ secrets.GH_TOKEN }}



