name: "calling_workflow"
on:
  workflow_call:
  workflow_dispatch:
  push:
  
jobs:
  call-workflow-1-in-local-repo:
      uses: Tech-it-or-live-it-Secure-CICD/centralWorkflows/.github/workflows/centralGITLEAKS.yml@main
      secrets: inherit
  call-event-shower:
      uses: Tech-it-or-live-it-Secure-CICD/centralWorkflows/.github/workflows/showEVENT.yml@main
  call_central_depcheck:
      uses: Tech-it-or-live-it-Secure-CICD/centralWorkflows/.github/workflows/centralAPIdependencycheck.yml@main
  call_use_through_secret:
      uses: ${{ secrets.HOST }}/centralWorkflows/.github/workflows/centralAPIdependencycheck.yml@main
   


        





    #uses: ${{ github.repository_owner }}/centralWorkflows/.github/workflows/centralTEST.yml@main
