name: "calling_workflow"
on:
  workflow_call:
  workflow_dispatch:

jobs:
  call-workflow-1-in-local-repo:
      uses: Tech-it-or-live-it-Secure-CICD/centralWorkflows/.github/workflows/centralTEST.yml@main
      secrets: inherit
  retrieveID:
   runs-on: ubuntu-latest
   steps:
   - run: echo "ID= $(jq '.repoNAME2.branchNAME2.anchoreID' Tech-it-or-live-it-Secure-CICD/centralWorkflows/engagementIDs.json)"

        





    #uses: ${{ github.repository_owner }}/centralWorkflows/.github/workflows/centralTEST.yml@main
